version: "3.8"

services:

  site:
    image: docsy/docsy-example
    build:
      context: .
    command: server --watch --noHTTPCache --poll 1000ms
    ports:
      - "1313:1313"
    volumes:
      - .:/src
